//
// @Author: Tan90degrees tangentninetydegrees@gmail.com
// @Date: 2023-03-30 04:19:29
// @LastEditors: Tan90degrees tangentninetydegrees@gmail.com
// @LastEditTime: 2023-04-19 12:01:27
// @FilePath: /icefs/protos/lowlevel/fuseKernel.proto
// @Description:
//
// Copyright (C) 2023 Tan90degrees <tangentninetydegrees@gmail.com>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: fuseKernel.proto

package icefsgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FuseAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode     uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Size      uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Blocks    uint64 `protobuf:"varint,3,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Atime     uint64 `protobuf:"varint,4,opt,name=atime,proto3" json:"atime,omitempty"`
	Mtime     uint64 `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Ctime     uint64 `protobuf:"varint,6,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Atimensec uint32 `protobuf:"varint,7,opt,name=atimensec,proto3" json:"atimensec,omitempty"`
	Mtimensec uint32 `protobuf:"varint,8,opt,name=mtimensec,proto3" json:"mtimensec,omitempty"`
	Ctimensec uint32 `protobuf:"varint,9,opt,name=ctimensec,proto3" json:"ctimensec,omitempty"`
	Mode      uint32 `protobuf:"varint,10,opt,name=mode,proto3" json:"mode,omitempty"`
	Nlink     uint32 `protobuf:"varint,11,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Uid       uint32 `protobuf:"varint,12,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid       uint32 `protobuf:"varint,13,opt,name=gid,proto3" json:"gid,omitempty"`
	Rdev      uint32 `protobuf:"varint,14,opt,name=rdev,proto3" json:"rdev,omitempty"`
	Blksize   uint32 `protobuf:"varint,15,opt,name=blksize,proto3" json:"blksize,omitempty"`
	Flags     uint32 `protobuf:"varint,16,opt,name=flags,proto3" json:"flags,omitempty"`
}

func (x *FuseAttr) Reset() {
	*x = FuseAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseAttr) ProtoMessage() {}

func (x *FuseAttr) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseAttr.ProtoReflect.Descriptor instead.
func (*FuseAttr) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{0}
}

func (x *FuseAttr) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FuseAttr) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FuseAttr) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *FuseAttr) GetAtime() uint64 {
	if x != nil {
		return x.Atime
	}
	return 0
}

func (x *FuseAttr) GetMtime() uint64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *FuseAttr) GetCtime() uint64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *FuseAttr) GetAtimensec() uint32 {
	if x != nil {
		return x.Atimensec
	}
	return 0
}

func (x *FuseAttr) GetMtimensec() uint32 {
	if x != nil {
		return x.Mtimensec
	}
	return 0
}

func (x *FuseAttr) GetCtimensec() uint32 {
	if x != nil {
		return x.Ctimensec
	}
	return 0
}

func (x *FuseAttr) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FuseAttr) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *FuseAttr) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FuseAttr) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *FuseAttr) GetRdev() uint32 {
	if x != nil {
		return x.Rdev
	}
	return 0
}

func (x *FuseAttr) GetBlksize() uint32 {
	if x != nil {
		return x.Blksize
	}
	return 0
}

func (x *FuseAttr) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type FuseOutHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Len    uint32 `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	Error  int32  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Unique uint64 `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *FuseOutHeader) Reset() {
	*x = FuseOutHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseOutHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseOutHeader) ProtoMessage() {}

func (x *FuseOutHeader) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseOutHeader.ProtoReflect.Descriptor instead.
func (*FuseOutHeader) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{1}
}

func (x *FuseOutHeader) GetLen() uint32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *FuseOutHeader) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *FuseOutHeader) GetUnique() uint64 {
	if x != nil {
		return x.Unique
	}
	return 0
}

type FuseEntryOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodeid         uint64    `protobuf:"varint,1,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	Generation     uint64    `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	EntryValid     uint64    `protobuf:"varint,3,opt,name=entry_valid,json=entryValid,proto3" json:"entry_valid,omitempty"`
	AttrValid      uint64    `protobuf:"varint,4,opt,name=attr_valid,json=attrValid,proto3" json:"attr_valid,omitempty"`
	EntryValidNsec uint32    `protobuf:"varint,5,opt,name=entry_valid_nsec,json=entryValidNsec,proto3" json:"entry_valid_nsec,omitempty"`
	AttrValidNsec  uint32    `protobuf:"varint,6,opt,name=attr_valid_nsec,json=attrValidNsec,proto3" json:"attr_valid_nsec,omitempty"`
	Attr           *FuseAttr `protobuf:"bytes,7,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *FuseEntryOut) Reset() {
	*x = FuseEntryOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseEntryOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseEntryOut) ProtoMessage() {}

func (x *FuseEntryOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseEntryOut.ProtoReflect.Descriptor instead.
func (*FuseEntryOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{2}
}

func (x *FuseEntryOut) GetNodeid() uint64 {
	if x != nil {
		return x.Nodeid
	}
	return 0
}

func (x *FuseEntryOut) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *FuseEntryOut) GetEntryValid() uint64 {
	if x != nil {
		return x.EntryValid
	}
	return 0
}

func (x *FuseEntryOut) GetAttrValid() uint64 {
	if x != nil {
		return x.AttrValid
	}
	return 0
}

func (x *FuseEntryOut) GetEntryValidNsec() uint32 {
	if x != nil {
		return x.EntryValidNsec
	}
	return 0
}

func (x *FuseEntryOut) GetAttrValidNsec() uint32 {
	if x != nil {
		return x.AttrValidNsec
	}
	return 0
}

func (x *FuseEntryOut) GetAttr() *FuseAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type FuseAttrOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrValid     uint64    `protobuf:"varint,1,opt,name=attr_valid,json=attrValid,proto3" json:"attr_valid,omitempty"`
	AttrValidNsec uint32    `protobuf:"varint,2,opt,name=attr_valid_nsec,json=attrValidNsec,proto3" json:"attr_valid_nsec,omitempty"`
	Dummy         uint32    `protobuf:"varint,3,opt,name=dummy,proto3" json:"dummy,omitempty"`
	Attr          *FuseAttr `protobuf:"bytes,4,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *FuseAttrOut) Reset() {
	*x = FuseAttrOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseAttrOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseAttrOut) ProtoMessage() {}

func (x *FuseAttrOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseAttrOut.ProtoReflect.Descriptor instead.
func (*FuseAttrOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{3}
}

func (x *FuseAttrOut) GetAttrValid() uint64 {
	if x != nil {
		return x.AttrValid
	}
	return 0
}

func (x *FuseAttrOut) GetAttrValidNsec() uint32 {
	if x != nil {
		return x.AttrValidNsec
	}
	return 0
}

func (x *FuseAttrOut) GetDummy() uint32 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

func (x *FuseAttrOut) GetAttr() *FuseAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type FuseOpenOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fh        uint64 `protobuf:"varint,1,opt,name=fh,proto3" json:"fh,omitempty"`
	OpenFlags uint32 `protobuf:"varint,2,opt,name=open_flags,json=openFlags,proto3" json:"open_flags,omitempty"`
}

func (x *FuseOpenOut) Reset() {
	*x = FuseOpenOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseOpenOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseOpenOut) ProtoMessage() {}

func (x *FuseOpenOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseOpenOut.ProtoReflect.Descriptor instead.
func (*FuseOpenOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{4}
}

func (x *FuseOpenOut) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

func (x *FuseOpenOut) GetOpenFlags() uint32 {
	if x != nil {
		return x.OpenFlags
	}
	return 0
}

type FuseWriteOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size    uint32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Padding uint32 `protobuf:"varint,2,opt,name=padding,proto3" json:"padding,omitempty"`
}

func (x *FuseWriteOut) Reset() {
	*x = FuseWriteOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseWriteOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseWriteOut) ProtoMessage() {}

func (x *FuseWriteOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseWriteOut.ProtoReflect.Descriptor instead.
func (*FuseWriteOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{5}
}

func (x *FuseWriteOut) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FuseWriteOut) GetPadding() uint32 {
	if x != nil {
		return x.Padding
	}
	return 0
}

type FuseStatFSOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks  uint64 `protobuf:"varint,1,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Bfree   uint64 `protobuf:"varint,2,opt,name=bfree,proto3" json:"bfree,omitempty"`
	Bavail  uint64 `protobuf:"varint,3,opt,name=bavail,proto3" json:"bavail,omitempty"`
	Files   uint64 `protobuf:"varint,4,opt,name=files,proto3" json:"files,omitempty"`
	Ffree   uint64 `protobuf:"varint,5,opt,name=ffree,proto3" json:"ffree,omitempty"`
	Bsize   uint32 `protobuf:"varint,6,opt,name=bsize,proto3" json:"bsize,omitempty"`
	Namelen uint32 `protobuf:"varint,7,opt,name=namelen,proto3" json:"namelen,omitempty"`
	Frsize  uint32 `protobuf:"varint,8,opt,name=frsize,proto3" json:"frsize,omitempty"`
}

func (x *FuseStatFSOut) Reset() {
	*x = FuseStatFSOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseStatFSOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseStatFSOut) ProtoMessage() {}

func (x *FuseStatFSOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseStatFSOut.ProtoReflect.Descriptor instead.
func (*FuseStatFSOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{6}
}

func (x *FuseStatFSOut) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *FuseStatFSOut) GetBfree() uint64 {
	if x != nil {
		return x.Bfree
	}
	return 0
}

func (x *FuseStatFSOut) GetBavail() uint64 {
	if x != nil {
		return x.Bavail
	}
	return 0
}

func (x *FuseStatFSOut) GetFiles() uint64 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *FuseStatFSOut) GetFfree() uint64 {
	if x != nil {
		return x.Ffree
	}
	return 0
}

func (x *FuseStatFSOut) GetBsize() uint32 {
	if x != nil {
		return x.Bsize
	}
	return 0
}

func (x *FuseStatFSOut) GetNamelen() uint32 {
	if x != nil {
		return x.Namelen
	}
	return 0
}

func (x *FuseStatFSOut) GetFrsize() uint32 {
	if x != nil {
		return x.Frsize
	}
	return 0
}

type FuseLkOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start uint64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   uint64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Type  uint32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Pid   uint32 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *FuseLkOut) Reset() {
	*x = FuseLkOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseLkOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseLkOut) ProtoMessage() {}

func (x *FuseLkOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseLkOut.ProtoReflect.Descriptor instead.
func (*FuseLkOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{7}
}

func (x *FuseLkOut) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *FuseLkOut) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *FuseLkOut) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FuseLkOut) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type FuseInitOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Major               uint32 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor               uint32 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	MaxReadahead        uint32 `protobuf:"varint,3,opt,name=max_readahead,json=maxReadahead,proto3" json:"max_readahead,omitempty"`
	Flags               uint32 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	MaxBackground       uint32 `protobuf:"varint,5,opt,name=max_background,json=maxBackground,proto3" json:"max_background,omitempty"`
	CongestionThreshold uint32 `protobuf:"varint,6,opt,name=congestion_threshold,json=congestionThreshold,proto3" json:"congestion_threshold,omitempty"`
	MaxWrite            uint32 `protobuf:"varint,7,opt,name=max_write,json=maxWrite,proto3" json:"max_write,omitempty"`
	TimeGran            uint32 `protobuf:"varint,8,opt,name=time_gran,json=timeGran,proto3" json:"time_gran,omitempty"`
	MaxPages            uint32 `protobuf:"varint,9,opt,name=max_pages,json=maxPages,proto3" json:"max_pages,omitempty"`
	MapAlignment        uint32 `protobuf:"varint,10,opt,name=map_alignment,json=mapAlignment,proto3" json:"map_alignment,omitempty"`
	Flags2              uint32 `protobuf:"varint,11,opt,name=flags2,proto3" json:"flags2,omitempty"`
}

func (x *FuseInitOut) Reset() {
	*x = FuseInitOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseInitOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseInitOut) ProtoMessage() {}

func (x *FuseInitOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseInitOut.ProtoReflect.Descriptor instead.
func (*FuseInitOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{8}
}

func (x *FuseInitOut) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *FuseInitOut) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *FuseInitOut) GetMaxReadahead() uint32 {
	if x != nil {
		return x.MaxReadahead
	}
	return 0
}

func (x *FuseInitOut) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *FuseInitOut) GetMaxBackground() uint32 {
	if x != nil {
		return x.MaxBackground
	}
	return 0
}

func (x *FuseInitOut) GetCongestionThreshold() uint32 {
	if x != nil {
		return x.CongestionThreshold
	}
	return 0
}

func (x *FuseInitOut) GetMaxWrite() uint32 {
	if x != nil {
		return x.MaxWrite
	}
	return 0
}

func (x *FuseInitOut) GetTimeGran() uint32 {
	if x != nil {
		return x.TimeGran
	}
	return 0
}

func (x *FuseInitOut) GetMaxPages() uint32 {
	if x != nil {
		return x.MaxPages
	}
	return 0
}

func (x *FuseInitOut) GetMapAlignment() uint32 {
	if x != nil {
		return x.MapAlignment
	}
	return 0
}

func (x *FuseInitOut) GetFlags2() uint32 {
	if x != nil {
		return x.Flags2
	}
	return 0
}

type FuseBmapOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block uint64 `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *FuseBmapOut) Reset() {
	*x = FuseBmapOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseBmapOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseBmapOut) ProtoMessage() {}

func (x *FuseBmapOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseBmapOut.ProtoReflect.Descriptor instead.
func (*FuseBmapOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{9}
}

func (x *FuseBmapOut) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

type FuseIoctlOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Flags   uint32 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	InIovs  uint32 `protobuf:"varint,3,opt,name=in_iovs,json=inIovs,proto3" json:"in_iovs,omitempty"`
	OutIovs uint32 `protobuf:"varint,4,opt,name=out_iovs,json=outIovs,proto3" json:"out_iovs,omitempty"`
}

func (x *FuseIoctlOut) Reset() {
	*x = FuseIoctlOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseIoctlOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseIoctlOut) ProtoMessage() {}

func (x *FuseIoctlOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseIoctlOut.ProtoReflect.Descriptor instead.
func (*FuseIoctlOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{10}
}

func (x *FuseIoctlOut) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *FuseIoctlOut) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *FuseIoctlOut) GetInIovs() uint32 {
	if x != nil {
		return x.InIovs
	}
	return 0
}

func (x *FuseIoctlOut) GetOutIovs() uint32 {
	if x != nil {
		return x.OutIovs
	}
	return 0
}

type FusePollOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revents uint32 `protobuf:"varint,1,opt,name=revents,proto3" json:"revents,omitempty"`
	Padding uint32 `protobuf:"varint,2,opt,name=padding,proto3" json:"padding,omitempty"`
}

func (x *FusePollOut) Reset() {
	*x = FusePollOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FusePollOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FusePollOut) ProtoMessage() {}

func (x *FusePollOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FusePollOut.ProtoReflect.Descriptor instead.
func (*FusePollOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{11}
}

func (x *FusePollOut) GetRevents() uint32 {
	if x != nil {
		return x.Revents
	}
	return 0
}

func (x *FusePollOut) GetPadding() uint32 {
	if x != nil {
		return x.Padding
	}
	return 0
}

type FuseNotifyPollWakeupOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kh uint64 `protobuf:"varint,1,opt,name=kh,proto3" json:"kh,omitempty"`
}

func (x *FuseNotifyPollWakeupOut) Reset() {
	*x = FuseNotifyPollWakeupOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseNotifyPollWakeupOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseNotifyPollWakeupOut) ProtoMessage() {}

func (x *FuseNotifyPollWakeupOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseNotifyPollWakeupOut.ProtoReflect.Descriptor instead.
func (*FuseNotifyPollWakeupOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{12}
}

func (x *FuseNotifyPollWakeupOut) GetKh() uint64 {
	if x != nil {
		return x.Kh
	}
	return 0
}

type FuseNotifyInvalInodeOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inode uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Off   int64  `protobuf:"varint,2,opt,name=off,proto3" json:"off,omitempty"`
	Len   int64  `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
}

func (x *FuseNotifyInvalInodeOut) Reset() {
	*x = FuseNotifyInvalInodeOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseNotifyInvalInodeOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseNotifyInvalInodeOut) ProtoMessage() {}

func (x *FuseNotifyInvalInodeOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseNotifyInvalInodeOut.ProtoReflect.Descriptor instead.
func (*FuseNotifyInvalInodeOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{13}
}

func (x *FuseNotifyInvalInodeOut) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FuseNotifyInvalInodeOut) GetOff() int64 {
	if x != nil {
		return x.Off
	}
	return 0
}

func (x *FuseNotifyInvalInodeOut) GetLen() int64 {
	if x != nil {
		return x.Len
	}
	return 0
}

type FuseNotifyInvalEntryOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent  uint64 `protobuf:"varint,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Namelen uint32 `protobuf:"varint,2,opt,name=namelen,proto3" json:"namelen,omitempty"`
}

func (x *FuseNotifyInvalEntryOut) Reset() {
	*x = FuseNotifyInvalEntryOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseNotifyInvalEntryOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseNotifyInvalEntryOut) ProtoMessage() {}

func (x *FuseNotifyInvalEntryOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseNotifyInvalEntryOut.ProtoReflect.Descriptor instead.
func (*FuseNotifyInvalEntryOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{14}
}

func (x *FuseNotifyInvalEntryOut) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *FuseNotifyInvalEntryOut) GetNamelen() uint32 {
	if x != nil {
		return x.Namelen
	}
	return 0
}

type FuseNotifyDeleteOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent  uint64 `protobuf:"varint,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Child   uint64 `protobuf:"varint,2,opt,name=child,proto3" json:"child,omitempty"`
	Namelen uint32 `protobuf:"varint,3,opt,name=namelen,proto3" json:"namelen,omitempty"`
}

func (x *FuseNotifyDeleteOut) Reset() {
	*x = FuseNotifyDeleteOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseNotifyDeleteOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseNotifyDeleteOut) ProtoMessage() {}

func (x *FuseNotifyDeleteOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseNotifyDeleteOut.ProtoReflect.Descriptor instead.
func (*FuseNotifyDeleteOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{15}
}

func (x *FuseNotifyDeleteOut) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *FuseNotifyDeleteOut) GetChild() uint64 {
	if x != nil {
		return x.Child
	}
	return 0
}

func (x *FuseNotifyDeleteOut) GetNamelen() uint32 {
	if x != nil {
		return x.Namelen
	}
	return 0
}

type FuseNotifyStoreOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodeid uint64 `protobuf:"varint,1,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size   uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FuseNotifyStoreOut) Reset() {
	*x = FuseNotifyStoreOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseNotifyStoreOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseNotifyStoreOut) ProtoMessage() {}

func (x *FuseNotifyStoreOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseNotifyStoreOut.ProtoReflect.Descriptor instead.
func (*FuseNotifyStoreOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{16}
}

func (x *FuseNotifyStoreOut) GetNodeid() uint64 {
	if x != nil {
		return x.Nodeid
	}
	return 0
}

func (x *FuseNotifyStoreOut) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FuseNotifyStoreOut) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FuseNotifyRetrieveOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotifyUnique uint64 `protobuf:"varint,1,opt,name=notify_unique,json=notifyUnique,proto3" json:"notify_unique,omitempty"`
	Nodeid       uint64 `protobuf:"varint,2,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	Offset       uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size         uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FuseNotifyRetrieveOut) Reset() {
	*x = FuseNotifyRetrieveOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseNotifyRetrieveOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseNotifyRetrieveOut) ProtoMessage() {}

func (x *FuseNotifyRetrieveOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseNotifyRetrieveOut.ProtoReflect.Descriptor instead.
func (*FuseNotifyRetrieveOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{17}
}

func (x *FuseNotifyRetrieveOut) GetNotifyUnique() uint64 {
	if x != nil {
		return x.NotifyUnique
	}
	return 0
}

func (x *FuseNotifyRetrieveOut) GetNodeid() uint64 {
	if x != nil {
		return x.Nodeid
	}
	return 0
}

func (x *FuseNotifyRetrieveOut) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FuseNotifyRetrieveOut) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FuseLseekOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *FuseLseekOut) Reset() {
	*x = FuseLseekOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuseKernel_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuseLseekOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseLseekOut) ProtoMessage() {}

func (x *FuseLseekOut) ProtoReflect() protoreflect.Message {
	mi := &file_fuseKernel_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseLseekOut.ProtoReflect.Descriptor instead.
func (*FuseLseekOut) Descriptor() ([]byte, []int) {
	return file_fuseKernel_proto_rawDescGZIP(), []int{18}
}

func (x *FuseLseekOut) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_fuseKernel_proto protoreflect.FileDescriptor

var file_fuseKernel_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x75, 0x73, 0x65, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x69, 0x63, 0x65, 0x66, 0x73, 0x67, 0x72, 0x70, 0x63, 0x22, 0xfa, 0x02,
	0x0a, 0x08, 0x46, 0x75, 0x73, 0x65, 0x41, 0x74, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x61, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x74,
	0x69, 0x6d, 0x65, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63,
	0x74, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x6c, 0x69,
	0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x64, 0x65, 0x76, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x64, 0x65, 0x76, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c,
	0x6b, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x6c, 0x6b,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x4f, 0x0a, 0x0d, 0x46, 0x75,
	0x73, 0x65, 0x4f, 0x75, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x22, 0x81, 0x02, 0x0a, 0x0c,
	0x46, 0x75, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x5f, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4e, 0x73, 0x65, 0x63, 0x12, 0x26,
	0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x6e, 0x73, 0x65,
	0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x4e, 0x73, 0x65, 0x63, 0x12, 0x27, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x63, 0x65, 0x66, 0x73, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x46, 0x75, 0x73, 0x65, 0x41, 0x74, 0x74, 0x72, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x22,
	0x93, 0x01, 0x0a, 0x0b, 0x46, 0x75, 0x73, 0x65, 0x41, 0x74, 0x74, 0x72, 0x4f, 0x75, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x26,
	0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x6e, 0x73, 0x65,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x4e, 0x73, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x27, 0x0a, 0x04,
	0x61, 0x74, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x63, 0x65,
	0x66, 0x73, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x75, 0x73, 0x65, 0x41, 0x74, 0x74, 0x72, 0x52,
	0x04, 0x61, 0x74, 0x74, 0x72, 0x22, 0x3c, 0x0a, 0x0b, 0x46, 0x75, 0x73, 0x65, 0x4f, 0x70, 0x65,
	0x6e, 0x4f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x66, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x46, 0x6c,
	0x61, 0x67, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x46, 0x75, 0x73, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x4f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x64, 0x64, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x61, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x22, 0xc9, 0x01, 0x0a, 0x0d, 0x46, 0x75, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x46, 0x53,
	0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x66, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x66, 0x72, 0x65,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x62, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x66, 0x72, 0x65, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x66, 0x66, 0x72, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x61, 0x6d, 0x65, 0x6c, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x61,
	0x6d, 0x65, 0x6c, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x66, 0x72, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x59, 0x0a,
	0x09, 0x46, 0x75, 0x73, 0x65, 0x4c, 0x6b, 0x4f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0xe2, 0x02, 0x0a, 0x0b, 0x46, 0x75, 0x73,
	0x65, 0x49, 0x6e, 0x69, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x6a, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d,
	0x69, 0x6e, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x65, 0x61, 0x64,
	0x61, 0x68, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6d, 0x61, 0x78,
	0x52, 0x65, 0x61, 0x64, 0x61, 0x68, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12,
	0x25, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x42, 0x61, 0x63, 0x6b,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x31, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78,
	0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61,
	0x78, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x67,
	0x72, 0x61, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x47,
	0x72, 0x61, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x50, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x70, 0x5f, 0x61, 0x6c, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6d, 0x61, 0x70, 0x41, 0x6c, 0x69, 0x67,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x32, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x32, 0x22, 0x23, 0x0a,
	0x0b, 0x46, 0x75, 0x73, 0x65, 0x42, 0x6d, 0x61, 0x70, 0x4f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x22, 0x70, 0x0a, 0x0c, 0x46, 0x75, 0x73, 0x65, 0x49, 0x6f, 0x63, 0x74, 0x6c, 0x4f,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c,
	0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x6e, 0x5f, 0x69, 0x6f, 0x76, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x69, 0x6e, 0x49, 0x6f, 0x76, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x75, 0x74,
	0x5f, 0x69, 0x6f, 0x76, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6f, 0x75, 0x74,
	0x49, 0x6f, 0x76, 0x73, 0x22, 0x41, 0x0a, 0x0b, 0x46, 0x75, 0x73, 0x65, 0x50, 0x6f, 0x6c, 0x6c,
	0x4f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x70, 0x61, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x29, 0x0a, 0x17, 0x46, 0x75, 0x73, 0x65, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x6f, 0x6c, 0x6c, 0x57, 0x61, 0x6b, 0x65, 0x75, 0x70, 0x4f,
	0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6b, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x6b, 0x68, 0x22, 0x53, 0x0a, 0x17, 0x46, 0x75, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6f, 0x66, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x22, 0x4b, 0x0a, 0x17, 0x46, 0x75, 0x73, 0x65, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4f,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x61,
	0x6d, 0x65, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x61, 0x6d,
	0x65, 0x6c, 0x65, 0x6e, 0x22, 0x5d, 0x0a, 0x13, 0x46, 0x75, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x61, 0x6d,
	0x65, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x61, 0x6d, 0x65,
	0x6c, 0x65, 0x6e, 0x22, 0x58, 0x0a, 0x12, 0x46, 0x75, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x80, 0x01,
	0x0a, 0x15, 0x46, 0x75, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x5f, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0x26, 0x0a, 0x0c, 0x46, 0x75, 0x73, 0x65, 0x4c, 0x73, 0x65, 0x65, 0x6b, 0x4f, 0x75, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x69,
	0x63, 0x65, 0x66, 0x73, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fuseKernel_proto_rawDescOnce sync.Once
	file_fuseKernel_proto_rawDescData = file_fuseKernel_proto_rawDesc
)

func file_fuseKernel_proto_rawDescGZIP() []byte {
	file_fuseKernel_proto_rawDescOnce.Do(func() {
		file_fuseKernel_proto_rawDescData = protoimpl.X.CompressGZIP(file_fuseKernel_proto_rawDescData)
	})
	return file_fuseKernel_proto_rawDescData
}

var file_fuseKernel_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_fuseKernel_proto_goTypes = []interface{}{
	(*FuseAttr)(nil),                // 0: icefsgrpc.FuseAttr
	(*FuseOutHeader)(nil),           // 1: icefsgrpc.FuseOutHeader
	(*FuseEntryOut)(nil),            // 2: icefsgrpc.FuseEntryOut
	(*FuseAttrOut)(nil),             // 3: icefsgrpc.FuseAttrOut
	(*FuseOpenOut)(nil),             // 4: icefsgrpc.FuseOpenOut
	(*FuseWriteOut)(nil),            // 5: icefsgrpc.FuseWriteOut
	(*FuseStatFSOut)(nil),           // 6: icefsgrpc.FuseStatFSOut
	(*FuseLkOut)(nil),               // 7: icefsgrpc.FuseLkOut
	(*FuseInitOut)(nil),             // 8: icefsgrpc.FuseInitOut
	(*FuseBmapOut)(nil),             // 9: icefsgrpc.FuseBmapOut
	(*FuseIoctlOut)(nil),            // 10: icefsgrpc.FuseIoctlOut
	(*FusePollOut)(nil),             // 11: icefsgrpc.FusePollOut
	(*FuseNotifyPollWakeupOut)(nil), // 12: icefsgrpc.FuseNotifyPollWakeupOut
	(*FuseNotifyInvalInodeOut)(nil), // 13: icefsgrpc.FuseNotifyInvalInodeOut
	(*FuseNotifyInvalEntryOut)(nil), // 14: icefsgrpc.FuseNotifyInvalEntryOut
	(*FuseNotifyDeleteOut)(nil),     // 15: icefsgrpc.FuseNotifyDeleteOut
	(*FuseNotifyStoreOut)(nil),      // 16: icefsgrpc.FuseNotifyStoreOut
	(*FuseNotifyRetrieveOut)(nil),   // 17: icefsgrpc.FuseNotifyRetrieveOut
	(*FuseLseekOut)(nil),            // 18: icefsgrpc.FuseLseekOut
}
var file_fuseKernel_proto_depIdxs = []int32{
	0, // 0: icefsgrpc.FuseEntryOut.attr:type_name -> icefsgrpc.FuseAttr
	0, // 1: icefsgrpc.FuseAttrOut.attr:type_name -> icefsgrpc.FuseAttr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fuseKernel_proto_init() }
func file_fuseKernel_proto_init() {
	if File_fuseKernel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fuseKernel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseOutHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseEntryOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseAttrOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseOpenOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseWriteOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseStatFSOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseLkOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseInitOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseBmapOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseIoctlOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FusePollOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseNotifyPollWakeupOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseNotifyInvalInodeOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseNotifyInvalEntryOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseNotifyDeleteOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseNotifyStoreOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseNotifyRetrieveOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuseKernel_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuseLseekOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fuseKernel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fuseKernel_proto_goTypes,
		DependencyIndexes: file_fuseKernel_proto_depIdxs,
		MessageInfos:      file_fuseKernel_proto_msgTypes,
	}.Build()
	File_fuseKernel_proto = out.File
	file_fuseKernel_proto_rawDesc = nil
	file_fuseKernel_proto_goTypes = nil
	file_fuseKernel_proto_depIdxs = nil
}
